### ISSUE TITLE
Please add user documentation to GitHub

### ISSUE THREAD

**Issue by Yvan-Masson** [tranquilit/WAPT#1]
Hi,

First thanks for all your work.

I can not find the WAPT user documentation (https://www.wapt.fr/en/doc/index.html) on GitHub. Could you add it so that others can help improving it?

Regards,
Yvan

**Comment by d-cardon** [comment]
Hi Yvan,

the official documentation is currently hosted on our internal git. We hope that we can publish the rst sphinx tree on our public github soon. For historical reasons the main documentation is in French and then translated in English using sphinx-intl. We need to find time to do a "poswap" so that English version is becoming the main one and French be a translation. Once we have done this "poswap" then we will publish the source on tranquilit github public repo and start accepting pull requests.

By the way, which part of the documentation you'd want to see improved?

Cheers,
Denis

**Comment by Yvan-Masson** [comment]
Hi,

Thanks for the answer. That is exactly what I wanted to improve: English and French translation (sometimes it is in French, sometimes it is in English). Also, I think I have seen a few typos around.

I would not be able to help on this, but a basic python examples of available functions would be really great.

But I might not help in the near future : I left WAPT, which is really promising, but it had some issues for my usage (it is really possible I did not understand how to use it). From my memory:
- I could not find a way to test a new package version on some clients without affecting all clients
- I could not find a way to set a default group of packages for all clients
- Some actions in the console (I don't remember exactly, sorry) would have required to click on each client one by one

Best regards,
Yvan

**Comment by d-cardon** [comment]
Hi Yvan,

I think most of your concerns can be overcome. You should subscribe to the forum or the mailing list to ask those questions. There are thousands of sysadmin using it, so even though there are obviously things to improve in WAPT, most sysadmin find ways to set it up in a useful way!

Since november we have released WAPT 1.5, which provides quite a few enhancement compared to the 1.3 version. You should give it a try :-)

Cheers,

Denis

**Comment by htouvet** [comment]
https://github.com/tranquilit/WAPT-Documentation
